- id: '1730719176903'
  alias: Brudi allein zuhause
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - zone.home
    to: '0'
  conditions:
  - alias: Letzter Reiningungsbeginn vor 2 Tagen
    condition: template
    value_template: '{{ now() - as_datetime(states(''sensor.brudi_letzter_reinigungsbeginn''))
      > timedelta(hours=36) }}'
  - condition: device
    device_id: 2eaf2281949db210683b1b6232825653
    domain: vacuum
    entity_id: f9e53740ef931d6bcc27511a79225b4b
    type: is_docked
  - condition: numeric_state
    entity_id: vacuum.brudi
    attribute: battery_level
    above: 50
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  actions:
  - device_id: 2eaf2281949db210683b1b6232825653
    domain: vacuum
    entity_id: f9e53740ef931d6bcc27511a79225b4b
    type: clean
  - action: script.durchsage
    data:
      notification: true
      announcement: true
      message: Der Hauself kommt und putzt während alle unterwegs sind!
  mode: single
- id: 97120b7c-481f-4899-8b2e-7960047f12cc
  alias: Kühlschrank immer einschalten
  triggers:
  - entity_id:
    - switch.kuhlschrank
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
    trigger: state
  actions:
  - target:
      entity_id:
      - switch.kuhlschrank
    action: switch.turn_on
    data: {}
  - data:
      announcement: true
      notification: true
      message: Kühlschrank war deaktiviert und wird wieder eingeschaltet.
    action: script.durchsage
  mode: single
- id: 84aa0cd5-0784-4b79-8b24-490f9d917c3b
  alias: Kühlschrank Stromverbrauch Warnung
  triggers:
  - entity_id:
    - sensor.kuhlschrank_power
    below: 10
    for:
      hours: 1
      minutes: 0
      seconds: 0
    trigger: numeric_state
  actions:
  - data:
      announcement: true
      notification: true
      message: Kühlschrank hat einen unerwartet geringen Stromverbrauch. Bitte prüfen.
    action: script.durchsage
  mode: single
- id: 4ca73738-3646-4a06-a127-6bc9ef15cef9
  alias: Licht Arbeitszimmer Taste 2
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 2
    trigger: event
  actions:
  - if:
    - condition: state
      entity_id: light.arbeitszimmer
      state: 'on'
    then:
    - target:
        entity_id:
        - light.arbeitszimmer
      data_template:
        brightness: '{{states.light.arbeitszimmer.attributes.brightness + 50}}'
      action: light.turn_on
  mode: single
- id: db35930b-e077-4f67-92ae-fdee812205f1
  alias: Licht Arbeitszimmer Taste 3
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 3
    trigger: event
  actions:
  - if:
    - condition: state
      entity_id: light.arbeitszimmer
      state: 'on'
    then:
    - target:
        entity_id:
        - light.arbeitszimmer
      data_template:
        brightness: '{{states.light.arbeitszimmer.attributes.brightness - 50}}'
      action: light.turn_on
  mode: single
- id: a773fa36-942b-4063-a404-69f5ce68cf9f
  alias: Lichtschalter
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 1
    id: arbeitszimmer
    trigger: event
    alias: Arbeitszimmer
  - event_type: hue_event
    event_data:
      id: lichtschalter_bad_button
      type: initial_press
      subtype: 1
    id: bad
    trigger: event
    alias: Bad
  - event_type: hue_event
    event_data:
      id: lichtschalter_flur_oben_button
      type: initial_press
      subtype: 1
    id: flur_oben
    trigger: event
    alias: Flur Oben
  - event_type: hue_event
    event_data:
      id: lichtschalter_hobbyzimmer_button
      type: initial_press
      subtype: 1
    id: hobbyzimmer
    trigger: event
    alias: Hobbyzimmer
  - event_type: hue_event
    event_data:
      id: lichtschalter_kuche_button
      type: initial_press
      subtype: 1
    id: lampe_arbeitsflache
    trigger: event
    alias: Arbeitsfläche
  - event_type: hue_event
    event_data:
      id: lichtschalter_kuche_button
      type: initial_press
      subtype: 2
    id: lampe_kuche
    trigger: event
    alias: Küche
  - event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 1
    id: nahzimmer
    trigger: event
    alias: Nähzimmer
  - event_type: hue_event
    event_data:
      id: lichtschalter_schlafzimmer_button
      type: initial_press
      subtype: 1
    id: schlafzimmer
    trigger: event
    alias: Schlafzimmer (Lichtschalter)
  - event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 1
    id: schlafzimmer
    trigger: event
    alias: Schlafzimmer (Fernbedienung)
  - event_type: hue_event
    event_data:
      id: lichtschalter_schrankzimmer_button
      type: initial_press
      subtype: 1
    id: schrankzimmer
    trigger: event
    alias: Schrankzimmer
  - event_type: hue_event
    event_data:
      id: lichtschalter_toilette_button
      type: initial_press
      subtype: 1
    id: toilette
    trigger: event
    alias: Toilette
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_sofa_button
      type: initial_press
      subtype: 1
    id: lampen_sofa
    trigger: event
    alias: Sofa
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_tur_button
      type: initial_press
      subtype: 1
    id: flur_keller
    trigger: event
    alias: Flur Keller
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_tur_button
      type: initial_press
      subtype: 2
    id: wohnzimmer
    trigger: event
    alias: Wohnzimmer (Lichtschalter an Tür)
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_treppe_button
      type: initial_press
      subtype: 1
    id: flur_oben
    trigger: event
    alias: Flur Oben (Lichtschalter im Wohnzimmer)
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_treppe_button
      type: initial_press
      subtype: 2
    id: wohnzimmer
    trigger: event
    alias: Wohnzimmer (Lichtschalter an Treppe))
  actions:
  - target:
      entity_id:
      - light.{{ trigger.id }}
    action: light.toggle
  mode: single
- id: f2b59cb1-c9e9-4b85-998e-052cf7957cb6
  alias: Licht Nähzimmer Taste 4
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 4
    trigger: event
  actions:
  - data:
      entity_id: switch.adaptive_lighting_light
      manual_control: true
      lights:
      - light.nahzimmer
    action: adaptive_lighting.set_manual_control
  - target:
      entity_id: scene.nahzimmer_lesen
    action: scene.turn_on
    data: {}
  mode: single
- id: 65e8281c-6645-4866-b504-06866a294a57
  alias: Licht Schlafzimmer Taste 2
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 2
    trigger: event
  actions:
  - if:
    - condition: state
      entity_id: light.schlafzimmer
      state: 'on'
    then:
    - target:
        entity_id:
        - light.schlafzimmer
      data_template:
        brightness: '{{states.light.schlafzimmer.attributes.brightness + 50}}'
      action: light.turn_on
  mode: single
- id: eda9e512-a286-4b13-8a25-159405c425a3
  alias: Licht Schlafzimmer Taste 3
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 3
    trigger: event
  actions:
  - if:
    - condition: state
      entity_id: light.schlafzimmer
      state: 'on'
    then:
    - target:
        entity_id:
        - light.schlafzimmer
      data_template:
        brightness: '{{states.light.schlafzimmer.attributes.brightness - 50}}'
      action: light.turn_on
  mode: single
- id: 82700968-4d9f-4f60-9e40-01a5a299eb32
  alias: Licht Schlafzimmer Taste 4
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 4
    trigger: event
  actions:
  - data:
      entity_id: switch.adaptive_lighting_dark
      manual_control: true
      lights:
      - light.schlafzimmer
    action: adaptive_lighting.set_manual_control
  - target:
      entity_id: scene.schlafzimmer_kuhles_helles_licht
    action: scene.turn_on
    data: {}
  mode: single
- id: 8a5468ef-e8a1-48eb-8f5d-26848022c36c""
  alias: Stromschalter
  triggers:
  - event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 4
    id: arbeitsplatz_stefan
    trigger: event
    alias: Arbeitsplatz Stefan
  - event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 2
    id: nahplatz
    trigger: event
    alias: Nähplatz
  - event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 3
    id: arbeitsplatz_anna
    trigger: event
    alias: Arbeitsplatz Anna
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_sofa_button
      type: initial_press
      subtype: 2
    id: multimedia
    trigger: event
    alias: Multimedia
  actions:
  - target:
      entity_id:
      - switch.{{ trigger.id }}
    action: switch.toggle
  mode: single
- id: 1789f124-d864-4ef6-bb9f-6102c37f4633""
  alias: Licht Wohnzimmer Essen
  triggers:
  - event_type: hue_event
    event_data:
      id: lichtschalter_wohnzimmer_essen_button
      type: initial_press
      subtype: 1
    trigger: event
  actions:
  - if:
    - condition: state
      entity_id: light.wohnzimmer
      state: 'on'
    then:
    - target:
        entity_id:
        - light.wohnzimmer
      action: light.turn_off
      data: {}
    else:
    - data:
        entity_id: switch.adaptive_lighting_dark
        manual_control: true
        lights:
        - light.lampe_esstisch
        - light.lampe_esszimmer
      action: adaptive_lighting.set_manual_control
    - target:
        entity_id: scene.essen
      action: scene.turn_on
      data: {}
  mode: single
- id: f86bade4-38f7-4744-8d0a-13b2bdbc6a7a
  alias: Wohnzimmer Kinomodus
  triggers:
  - entity_id:
    - media_player.wohnzimmer_tv
    to: playing
    id: start_playing
    trigger: state
  - entity_id:
    - media_player.wohnzimmer_tv
    to: paused
    id: stop_playing
    trigger: state
  - entity_id:
    - media_player.wohnzimmer_tv
    from: 'off'
    id: start_playing
    trigger: state
  - entity_id:
    - media_player.wohnzimmer_tv
    to: 'off'
    id: stop_playing
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sensor.multimedia_power
    above: 100
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - start_playing
      sequence:
      - target:
          entity_id: light.wohnzimmer
        action: light.turn_off
        data: {}
      - if:
        - condition: state
          entity_id: person.anna
          state: home
        - condition: state
          entity_id: zone.home
          state: '1'
        then:
        - target:
            entity_id: light.lampe_esszimmer
          action: light.turn_on
          data: {}
    - conditions:
      - condition: trigger
        id:
        - stop_playing
      sequence:
      - target:
          entity_id:
          - light.lichtschlauch_wohnzimmerregal
          - light.lampe_sofa
          - light.lampe_flur
        action: light.turn_on
        data: {}
  mode: single
- id: 9a4bbe68-6c6d-4d84-acec-a6f9cf830369
  alias: Bewegung im Flur Keller
  triggers:
  - entity_id:
    - binary_sensor.bewegungsmelder_flur_keller_bewegung
    to: 'on'
    trigger: state
  actions:
  - target:
      entity_id:
      - light.flur_keller
    action: light.turn_on
    data: {}
  - wait_for_trigger:
    - entity_id: binary_sensor.bewegungsmelder_flur_keller_bewegung
      to: 'off'
      trigger: state
  - delay:
      seconds: 15
  - target:
      entity_id:
      - light.flur_keller
    action: light.turn_off
    data: {}
  mode: restart
- id: 86492dad-5522-4acc-a7a8-f72ed17a16c4
  alias: Bewegung im Vorratskeller
  triggers:
  - entity_id:
    - binary_sensor.bewegungsmelder_vorratskeller_bewegung
    to: 'on'
    trigger: state
  actions:
  - target:
      entity_id:
      - light.vorratskeller
    action: light.turn_on
    data: {}
  - wait_for_trigger:
    - entity_id: binary_sensor.bewegungsmelder_vorratskeller_bewegung
      to: 'off'
      trigger: state
  - delay:
      seconds: 60
  - target:
      entity_id:
      - light.vorratskeller
    action: light.turn_off
    data: {}
  mode: restart
- id: 75d6d40b-0ece-47f4-99fe-cc681d02eb1a
  alias: Bewegung in der Waschküche
  triggers:
  - entity_id:
    - binary_sensor.bewegungsmelder_waschkuche_bewegung
    to: 'on'
    trigger: state
  actions:
  - target:
      entity_id:
      - light.waschkuche
    action: light.turn_on
    data: {}
  - wait_for_trigger:
    - entity_id: binary_sensor.bewegungsmelder_waschkuche_bewegung
      to: 'off'
      trigger: state
  - delay:
      seconds: 60
  - target:
      entity_id:
      - light.waschkuche
    action: light.turn_off
    data: {}
  mode: restart
- id: fa841bc4-dad3-4506-a92a-fa7e653d4204
  alias: Bewegung im Windfang
  triggers:
  - entity_id:
    - binary_sensor.bewegungsmelder_windfang_bewegung
    to: 'on'
    trigger: state
  conditions:
  - or:
    - condition: numeric_state
      entity_id: sensor.bewegungsmelder_windfang_beleuchtungsstarke
      below: 12
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  actions:
  - target:
      entity_id:
      - light.windfang
    action: light.turn_on
    data: {}
  - wait_for_trigger:
    - entity_id: binary_sensor.bewegungsmelder_windfang_bewegung
      to: 'off'
      trigger: state
  - delay:
      seconds: 15
  - target:
      entity_id:
      - light.windfang
    action: light.turn_off
    data: {}
  mode: restart
- id: 5d194104-8db9-4b6d-a37a-47920ce69e2f
  alias: Luftreiniger ausschalten
  triggers:
  - entity_id:
    - sensor.infeed_power
    for:
      minutes: 5
    below: 1
    trigger: numeric_state
  - at: '23:00:00'
    trigger: time
  conditions:
  - condition: state
    entity_id: fan.luftreiniger
    state: 'on'
  actions:
  - target:
      entity_id:
      - fan.luftreiniger
    action: fan.turn_off
    data: {}
  mode: single
- id: 6994ef61-e815-41b7-8c06-25529c8e4970
  alias: Luftreiniger einschalten
  triggers:
  - entity_id:
    - sensor.infeed_power
    for:
      minutes: 1
    above: 40
    trigger: numeric_state
  - at: '11:00:00'
    trigger: time
  conditions:
  - condition: state
    entity_id: fan.luftreiniger
    state: 'off'
  - condition: time
    after: '10:59:59'
    before: '23:00:00'
  - condition: numeric_state
    entity_id: sensor.infeed_power
    above: 40
  actions:
  - target:
      entity_id: fan.luftreiniger
    action: fan.turn_on
    data: {}
  mode: single
- id: 530e46b4-f669-4124-8557-1dbcaadb5c6d
  alias: Stromeinspeisung
  triggers:
  - entity_id:
    - sensor.infeed_power
    for:
      minutes: 5
    above: 50
    trigger: numeric_state
  actions:
  - data:
      announcement: true
      notification: true
      message: Wir schenken den Stadtwerken Strom!
    action: script.durchsage
  mode: single
- id: 9b9f6a10-ba36-4ff4-a60c-1bb29d78f672
  alias: Kaffeemaschine am Morgen
  triggers:
  - entity_id:
    - sensor.smart_series_8000_4c24_toothbrush_state
    to: running
    for:
      seconds: 30
    trigger: state
  conditions:
  - condition: time
    after: 07:30:00
    before: '15:00:00'
  actions:
  - target:
      entity_id:
      - switch.kuchenkleingerate
    action: switch.turn_on
    data: {}
  - delay:
      hours: 1
  - target:
      entity_id:
      - switch.kuchenkleingerate
    action: switch.turn_off
    data: {}
  mode: single
- id: 1c02fe5b-4809-4b3b-b023-2abf624159fd
  alias: Niemand zuhause
  triggers:
  - entity_id:
    - zone.home
    to: '0'
    for:
      minutes: 3
    id: Es wurde niemand mehr zuhause erkannt ich schalte nun alle Geräte ab
    trigger: state
  - event_type: hue_event
    event_data:
      id: lichtschalter_eingangstur_button
      type: initial_press
      subtype: 1
    id: Bis bald ich schalte nun alle Geräte ab
    trigger: event
  actions:
  - data:
      announcement: true
      notification: false
      message: '{{ trigger.id }}'
    action: script.durchsage
  - data:
      entity_id: all
    action: light.turn_off
  - target:
      entity_id:
      - switch.arbeitsplatz_anna
      - switch.hobbyzimmer
      - switch.kuchenkleingerate
      - switch.multimedia
      - switch.nahplatz
    action: switch.turn_off
    data: {}
  mode: single
- id: ae92745c-752d-4703-a10a-237148be05b0
  alias: Willkommen Zuhause
  triggers:
  - entity_id: person.anna
    to: home
    id: Willkommen Zuhause Anna
    trigger: state
  - entity_id: person.bine
    to: home
    id: Willkommen Zuhause Bine
    trigger: state
  - entity_id: person.cristina
    to: home
    id: Willkommen Cristina
    trigger: state
  - entity_id: person.stefan
    to: home
    id: Willkommen Zuhause Stefan
    trigger: state
  actions:
  - data:
      announcement: true
      notification: false
      message: '{{ trigger.id }}'
    action: script.durchsage
  mode: single
- id: fe5529ff-61fd-4f52-9cac-94194374719c
  alias: Annas Arbeitstag beginnt
  triggers:
  - at: 08:25:00
    trigger: time
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: person.anna
    state: home
  actions:
  - target:
      entity_id:
      - switch.arbeitsplatz_anna
    action: switch.turn_on
    data: {}
  mode: single
- id: d72596b8-db9d-43c2-b7ed-887021e742fc
  alias: Stefans Arbeitstag beginnt
  triggers:
  - at: 09:00:00
    trigger: time
  conditions:
  - condition: time
    weekday:
    - mon
    - fri
  - condition: state
    entity_id: person.stefan
    state: home
  actions:
  - target:
      entity_id:
      - switch.arbeitsplatz_stefan
    action: switch.turn_on
    data: {}
  mode: single
