---
- id: '1661697127963'
  alias: Bewegung im Windfang
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_windfang_motion
    to: 'on'
  condition: []
  action:
  - if:
    - and:
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
    then:
    - if:
      - condition: numeric_state
        entity_id: sensor.bewegungsmelder_windfang_illuminance
        above: '12'
      then:
      - if:
        - condition: state
          entity_id: scene.windfang_hell
          state: 'off'
        then:
        - stop: ''
      else:
      - service: scene.turn_on
        target:
          entity_id: scene.windfang_hell
        metadata: {}
    else:
    - service: scene.turn_on
      target:
        entity_id: scene.windfang_gedimmt
      metadata: {}
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.bewegungsmelder_windfang_motion
      to: 'off'
  - delay:
      seconds: 15
  - type: turn_off
    device_id: b6004a9f3fa7fbd88f4e9bd24fb55e03
    entity_id: light.windfang
    domain: light
  mode: restart
- id: '1670428711819'
  alias: Hue Wall Module schaltet Licht ohne Hue App
  description: ''
  trigger:
  - device_id: 08264d6f28ab365e34f8c5238a0cd179
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 722edaf9-f70e-4396-98ec-ac5ee5cf30f1
  condition: []
  action:
  - type: toggle
    device_id: cbc147ee93850260004f81ccdda186ee
    entity_id: light.lampe_schlafzimmer
    domain: light
  mode: single
- id: '1670770545594'
  alias: Weihnachtsmodus
  description: ''
  trigger: []
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.erdgeschoss_weihnachten
    metadata: {}
  - service: media_player.play_media
    target:
      entity_id: media_player.spotify_stefan
    data:
      media_content_id: https://open.spotify.com/playlist/37i9dQZF1DX3h1vasAdBTc?si=bolZs2G9RdmpxYTRMy60cg
      media_content_type: playlist
    metadata: {}
  - service: media_player.select_source
    data:
      source: Wohnzimmer
    target:
      entity_id: media_player.spotify_stefan
  mode: single
