---
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Data recording
recorder:
  # Commit only every 30 seconds to save the sd card of the raspberrz pi
  commit_interval: 0

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
