---
# Loads default set of integrations. Do not remove.
default_config:

# Data recording
recorder:
  # Commit only every 30 seconds to save the sd card of the raspberry pi
  commit_interval: 30

automation: !include automations.yaml
script: !include scripts.yaml
script split: !include_dir_list scripts
scene: !include scenes.yaml
scene split: !include_dir_list scenes

homeassistant:
  packages: !include_dir_named packages
