---
id: "9a4bbe68-6c6d-4d84-acec-a6f9cf830369"
alias: Bewegung im Flur Keller
trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_flur_keller_bewegung
    to: "on"
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.flur_keller
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_keller_bewegung
        to: "off"
  - delay:
      seconds: 15
  - service: light.turn_off
    target:
      entity_id:
        - light.flur_keller
mode: restart
