---
id: "86492dad-5522-4acc-a7a8-f72ed17a16c4"
alias: Bewegung im Vorratskeller
trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_vorratskeller_bewegung
    to: "on"
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.vorratskeller
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_vorratskeller_bewegung
        to: "off"
  - delay:
      seconds: 60
  - service: light.turn_off
    target:
      entity_id:
        - light.vorratskeller
mode: restart
