---
alias: Bewegung im Windfang
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_windfang_motion
    to: "on"
condition: []
action:
  - if:
      - and:
          - condition: sun
            after: sunrise
          - condition: sun
            before: sunset
    then:
      - if:
          - condition: numeric_state
            entity_id: sensor.bewegungsmelder_windfang_illuminance
            above: "12"
        then:
          - if:
              - condition: state
                entity_id: scene.windfang_hell
                state: "off"
            then:
              - stop: ""
        else:
          - service: scene.turn_on
            target:
              entity_id: scene.windfang_hell
            metadata: {}
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.windfang_gedimmt
        metadata: {}
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_windfang_motion
        to: "off"
  - delay:
      seconds: 15
  - type: turn_off
    device_id: b6004a9f3fa7fbd88f4e9bd24fb55e03
    entity_id: light.windfang
    domain: light
mode: restart
