---
id: "fa841bc4-dad3-4506-a92a-fa7e653d4204"
alias: Bewegung im Windfang
trigger:
  - platform: state
    entity_id: binary_sensor.bewegungsmelder_windfang_bewegung
    to: "on"
condition:
  - or:
      - condition: numeric_state
        entity_id: sensor.bewegungsmelder_windfang_beleuchtungsstarke
        below: 12
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.windfang
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_windfang_bewegung
        to: "off"
  - delay:
      seconds: 15
  - service: light.turn_off
    target:
      entity_id:
        - light.windfang
mode: restart
