---
id: "5d194104-8db9-4b6d-a37a-47920ce69e2f"
alias: Luftreiniger ausschalten
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.infeed_power
    for:
      minutes: 5
    below: 1
  - platform: time
    at: "23:00:00"
condition:
  - condition: state
    entity_id: fan.luftreiniger
    state: "on"
action:
  - service: fan.turn_off
    target:
      entity_id:
        - fan.luftreiniger
mode: single
