---
id: "530e46b4-f669-4124-8557-1dbcaadb5c6d"
alias: Stromeinspeisung
trigger:
  - platform: numeric_state
    entity_id: sensor.infeed_power
    for:
      minutes: 5
    above: 50
action:
  - service: script.durchsage
    data:
      announcement: true
      notification: true
      message: Wir schenken den Stadtwerken Strom!
mode: single
