---
id: "4ca73738-3646-4a06-a127-6bc9ef15cef9"
alias: Licht Arbeitszimmer Taste 2
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 2
action:
  - if:
      - condition: state
        entity_id: light.arbeitszimmer
        state: "on"
    then:
      - service: light.turn_on
        target:
          entity_id:
            - light.arbeitszimmer
        data_template:
          brightness: "{{states.light.arbeitszimmer.attributes.brightness + 50}}"
mode: single
