---
id: "234910955523"
alias: Licht Arbeitszimmer Taste 1
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.arbeitszimmer
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.arbeitszimmer
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.arbeitszimmer_naturliches_licht
mode: single
