---
id: "234910955523"
alias: Licht Arbeitszimmer Taste 1
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_arbeitszimmer_button
      type: initial_press
      subtype: 1
action:
  - service: light.toggle
    target:
      entity_id:
        - light.arbeitszimmer
mode: single
