---
id: "1881502763495"
alias: Licht Bad
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: lichtschalter_bad_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.bad
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.bad
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.bad_naturliches_licht
mode: single
