---
alias: Licht Bad
description: ""
trigger:
  - device_id: 08264d6f28ab365e34f8c5238a0cd179
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
condition: []
action:
  - if:
      - condition: state
        entity_id: light.bad
        state: "on"
    then:
      - type: turn_off
        device_id: 744a5d31d160ca62fcd4111d7b85c365
        entity_id: light.bad
        domain: light
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.bad_naturliches_licht
        metadata: {}
mode: single
