---
id: "45367029357"
alias: Licht Hobbyzimmer
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: lichtschalter_hobbyzimmer_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.hobbyzimmer
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.hobbyzimmer
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.hobbyzimmer_naturliches_licht
mode: single
