---
id: "424559878211"
alias: Licht Nähzimmer
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.nahzimmer
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.nahzimmer
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.nahzimmer_naturliches_licht
mode: single
