---
id: "2089635908542"
alias: Licht Nähzimmer Taste 2
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 2
action:
  - service: switch.toggle
    target:
      entity_id:
        - switch.nahplatz
mode: single
