---
id: "f2b59cb1-c9e9-4b85-998e-052cf7957cb6"
alias: Licht Nähzimmer Taste 4
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_nahzimmer_button
      type: initial_press
      subtype: 4
action:
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: switch.adaptive_lighting_light
      manual_control: true
      lights:
        - light.nahzimmer
  - service: scene.turn_on
    target:
      entity_id: scene.nahzimmer_entspannen
mode: single
