---
id: "1721283752607"
alias: Licht Schlafzimmer Taste 4
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 4
action:
  - service: scene.turn_on
    target:
      entity_id: scene.schlafzimmer_kuhles_helles_licht
mode: single
