---
id: "eda9e512-a286-4b13-8a25-159405c425a3"
alias: Licht Schlafzimmer Taste 3
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 3
action:
  - if:
      - condition: state
        entity_id: light.schlafzimmer
        state: "on"
    then:
      - service: light.turn_on
        target:
          entity_id:
            - light.schlafzimmer
        data_template:
          brightness: "{{states.light.schlafzimmer.attributes.brightness - 50}}"
mode: single
