---
alias: Licht Schlafzimmer
description: ""
trigger:
  - device_id: 7814eeb43b238498677b610f11330541
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
condition: []
action:
  - if:
      - condition: state
        entity_id: light.schlafzimmer
        state: "on"
    then:
      - type: turn_off
        device_id: eee8ce0f9159cd52bdad78792b8ad724
        entity_id: light.schlafzimmer
        domain: light
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.schlafzimmer_naturliches_licht
        metadata: {}
mode: single
