---
id: "492339624052"
alias: Licht Schlafzimmer Taste 1
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.schlafzimmer
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.schlafzimmer
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.schlafzimmer_naturliches_licht
mode: single
