---
id: "82700968-4d9f-4f60-9e40-01a5a299eb32"
alias: Licht Schlafzimmer Taste 4
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: fernbedienung_schlafzimmer_button
      type: initial_press
      subtype: 4
action:
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: switch.adaptive_lighting_dark
      manual_control: true
      lights:
        - light.schlafzimmer
  - service: scene.turn_on
    target:
      entity_id: scene.schlafzimmer_kuhles_helles_licht
mode: single
