---
id: "863677360"
alias: Licht Schrankzimmer
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: lichtschalter_schrankzimmer_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.schrankzimmer
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.schrankzimmer
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.schrankzimmer_naturliches_licht
mode: single
