---
id: "874166552"
alias: Licht Toilette
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      id: lichtschalter_toilette_button
      type: initial_press
      subtype: 1
action:
  - if:
      - condition: state
        entity_id: light.toilette
        state: "on"
    then:
      - service: light.turn_off
        target:
          entity_id:
            - light.toilette
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.toilette_naturliches_licht
mode: single
