---
id: f86bade4-38f7-4744-8d0a-13b2bdbc6a7a
alias: Wohnzimmer Kinomodus
trigger:
  # Triggers for the YouTube app
  - platform: state
    entity_id:
      - media_player.wohnzimmer_tv
    to: "playing"
    id: start_playing
  - platform: state
    entity_id:
      - media_player.wohnzimmer_tv
    to: "paused"
    id: stop_playing
  # Triggers for the RTL app
  - platform: state
    entity_id:
      - media_player.wohnzimmer_tv
    from: "off"
    id: start_playing
  - platform: state
    entity_id:
      - media_player.wohnzimmer_tv
    to: "off"
    id: stop_playing
condition:
  # Only if the projector is on.
  - condition: numeric_state
    entity_id: sensor.multimedia_power
    above: 100
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start_playing
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.wohnzimmer
          # If Anna is home alone, keep one light on.
          - if:
              - condition: state
                entity_id: person.anna
                state: "home"
              - condition: state
                entity_id: zone.home
                state: "1"
            then:
              - service: light.turn_on
                target:
                  entity_id: light.lampe_esszimmer
      - conditions:
          - condition: trigger
            id:
              - stop_playing
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.lichtschlauch_wohnzimmerregal
                - light.lampe_sofa
                - light.lampe_flur
mode: single
