# After using the toothbrush in the morning, switch on the coffee machine for an hour.
---
id: "1691144102868"
alias: Kaffeemaschine am Morgen
trigger:
  - platform: state
    entity_id:
      - sensor.smart_series_8000_4c24_toothbrush_state
    to: running
    for:
      seconds: 30
condition:
  - condition: time
    after: 07:30:00
    before: "15:00:00"
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.kuchenkleingerate
  - delay:
      hours: 1
  - service: switch.turn_off
    target:
      entity_id:
        - switch.kuchenkleingerate
mode: single
