---
id: "1c02fe5b-4809-4b3b-b023-2abf624159fd"
alias: Niemand zuhause
trigger:
  - platform: state
    entity_id:
      - zone.home
    to: "0"
    for:
      minutes: 3
    id: "Es wurde niemand mehr zuhause erkannt ich schalte nun alle Geräte ab"
  - platform: event
    event_type: hue_event
    event_data:
      id: lichtschalter_eingangstur_button
      type: initial_press
      subtype: 1
    id: "Bis bald ich schalte nun alle Geräte ab"
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.wohnzimmer
    data:
      media_content_id: >-
        media-source://tts/tts.piper?message={{ trigger.id | urlencode }}&language=de_DE&voice=de_DE-eva_k-x_low
      media_content_type: provider
  - delay: 5
  - service: light.turn_off
    data:
      entity_id: all
  - service: switch.turn_off
    target:
      entity_id:
        - switch.arbeitsplatz_anna
        - switch.hobbyzimmer
        - switch.kuchenkleingerate
        - switch.multimedia
        - switch.nahplatz
mode: single
