---
id: "530e46b4-f669-4124-8557-1dbcaadb5c6d"
alias: Stromeinspeisung
trigger:
  - platform: numeric_state
    entity_id: sensor.infeed_power
    for:
      minutes: 5
    above: 50
action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.wohnzimmer
      cache: true
      message: Wir schenken den Stadtwerken Strom! Bitte etwas einschalten!
      language: de
  - service: notify.notify
    data:
      title: "Die Sonne scheint stark! \U0001F31E"
      message: Wir schenken den Stadtwerken Strom! Können wir jetzt einen
        Stromverbraucher einschalten, der sowieso irgendwann laufen muss?
mode: single
