---
id: "ae92745c-752d-4703-a10a-237148be05b0"
alias: Willkommen Zuhause
trigger:
  - platform: state
    entity_id: person.anna
    to: "home"
    id: "Willkommen Zuhause Anna"
  - platform: state
    entity_id: person.cristina
    to: "home"
    id: "Willkommen Cristina"
  - platform: state
    entity_id: person.stefan
    to: "home"
    id: "Willkommen Zuhause Stefan"
action:
  - service: script.durchsage
    data:
      announcement: true
      notification: false
      message: "{{ trigger.id }}"
mode: single
