---
id: "1691579632657"
alias: Annas Arbeitstag beginnt
description: ""
trigger:
  - platform: time
    at: 08:25:00
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: person.anna
    state: home
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.arbeitsplatz_anna
mode: single
