---
id: "d72596b8-db9d-43c2-b7ed-887021e742fc"
alias: Stefans Arbeitstag beginnt
trigger:
  - platform: time
    at: 09:00:00
condition:
  - condition: time
    weekday:
      - mon
      - fri
  - condition: state
    entity_id: person.stefan
    state: home
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.arbeitsplatz_stefan
mode: single
