# Always keep the fridge switched on. Notify if someone turned it off accidentally.
---
id: "97120b7c-481f-4899-8b2e-7960047f12cc"
alias: Kühlschrank immer einschalten
trigger:
  - platform: state
    entity_id: switch.kuhlschrank
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
action:
  - service: switch.turn_on
    target:
      entity_id:
        - switch.kuhlschrank
  - service: notify.notify
    data:
      message: Kühlschrank war deaktiviert und wird wieder eingeschaltet.
mode: single
