# If the fridge is consuming less power than expected send a warning.
---
id: "84aa0cd5-0784-4b79-8b24-490f9d917c3b"
alias: Kühlschrank Stromverbrauch Warnung
trigger:
  - platform: numeric_state
    entity_id: sensor.kuhlschrank_power
    below: 10
    # No consumption for up to 40 minutes is regular behavior.
    for:
      hours: 1
      minutes: 0
      seconds: 0
action:
  - service: notify.notify
    data:
      message: Kühlschrank hat einen unerwartet geringen Stromverbrauch. Bitte prüfen.
mode: single
