# If the fridge is consuming less power than expected send a warning.
---
id: "1691246256034"
alias: Kühlschrank Stromverbrauch Warnung
description: ""
trigger:
  - type: power
    platform: device
    device_id: 7017a74f1f70e630d581c1e092a7eccc
    entity_id: switch.kuhlschrank
    domain: sensor
    below: 10
    # No consumption for up to 40 minutes is regular behavior.
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition: []
action:
  - service: notify.notify
    data:
      message: Kühlschrank hat einen unerwartet geringen Stromverbrauch. Bitte prüfen.
mode: single
