---
substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${name}

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${prefix} Fallback Hotspot"
    password: ${wifi_fallback_password}

captive_portal:

sensor:
  - platform: wifi_signal
    name: "${name} WLAN"
    id: sensor_wifi
    update_interval: 30s

  - platform: copy
    source_id: sensor_wifi
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    name: "${name} WLAN Empfang"
    unit_of_measurement: "%"

  - platform: uptime
    name: "${name} Uptime"
