---
# Temperature/humidity/pressure sensor BME280
substitutions:
  bme280_sda: GPIO21
  bme280_scl: GPIO22

i2c:
  sda: ${bme280_sda}
  scl: ${bme280_scl}
  scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "${prefix} Temperatur"
      oversampling: 16x
    pressure:
      name: "${prefix} Luftdruck"
    humidity:
      name: "${prefix} Luftfeuchtigkeit"
    address: 0x76
    update_interval: 30s
