---
# Temperature/humidity sensor DHT22
substitutions:
  dht22_pin: D4

sensor:
  - platform: dht
    pin: ${dht22_pin}
    model: DHT22
    temperature:
      name: "${prefix} Temperatur"
    humidity:
      name: "${prefix} Luftfeuchtigkeit"
      filters:
      - calibrate_linear:
        - 0.0 -> 0.0
        - 52.0 -> 40.0
        - 59.5 -> 45.0
    update_interval: 30s

