---
substitutions:
  name: "esp-arbeitszimmer"
  prefix: "Arbeitszimmer" 
  api_key: !secret arbeitszimmer_api_key
  ota_password: !secret arbeitszimmer_ota_password
  wifi_fallback_password: !secret arbeitszimmer_wifi_fallback_password

packages:
  device: !include .device.esp8266.yaml
  dht22: !include .sensor.dht22.yaml