---
substitutions:
  name: "esp-hobbyzimmer"
  prefix: "Hobbyzimmer" 
  api_key: !secret hobbyzimmer_api_key
  ota_password: !secret hobbyzimmer_ota_password
  wifi_fallback_password: !secret hobbyzimmer_wifi_fallback_password

packages:
  device: !include .device.esp32.yaml
  bme280: !include .sensor.bme280.yaml