---
esphome:
  name: esp-hobbyzimmer
  compile_process_limit: 1

esp8266:
  board: nodemcuv2

# Tempratur/humidity sensor DHT22
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    update_interval: 30s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hobbyzimmer_api_key

ota:
  password: !secret hobbyzimmer_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Hobbyzimmer Fallback Hotspot"
    password: !secret hobbyzimmer_wifi_fallback_password

captive_portal:
