---
substitutions:
  name: "esp-kueche"
  prefix: "Küche" 
  api_key: !secret kueche_api_key
  ota_password: !secret kueche_ota_password
  wifi_fallback_password: !secret kueche_wifi_fallback_password

packages:
  device: !include .device.esp8266.yaml
  dht22: !include .sensor.dht22.yaml