---
esphome:
  name: "esp-arbeitszimmer"

esp8266:
  board: nodemcuv2

# Tempratur/humidity sensor DHT22
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    update_interval: 30s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A9EgNX09Pet1wr6ax97FklxxE7ElDgWrzVd+AVmTRN8="

ota:
  password: "9cbd44a78562e4b1f43d73b1f06b11be"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Arbeitszimmer Fallback Hotspot"
    password: "HmhUkf6Z3PLd"

captive_portal:
    