---
esphome:
  name: esp-schlafzimmer

esp8266:
  board: nodemcuv2

# Tempratur/humidity sensor DHT22
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    update_interval: 30s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/sGm0zLRq3IAt1jWkWaF81R6aM2J26Y6R6PZ4n7uWpU="

ota:
  password: "f0db88210f8e198d057cba70a46af9c5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Schlafzimmer"
    password: "QtWgBhiPc77L"

captive_portal:
    