---
substitutions:
  name: "esp-wohnzimmer"
  prefix: "Wohnzimmer" 
  api_key: !secret wohnzimmer_api_key
  ota_password: !secret wohnzimmer_ota_password
  wifi_fallback_password: !secret wohnzimmer_wifi_fallback_password

packages:
  device: !include .device.esp32.yaml
  bme280: !include .sensor.bme280.yaml
