---
substitutions:
  name: "esp-schlafzimmer"
  prefix: "Schlafzimmer" 
  api_key: !secret schlafzimmer_api_key
  ota_password: !secret schlafzimmer_ota_password
  wifi_fallback_password: !secret schlafzimmer_wifi_fallback_password

packages:
  device: !include .device.esp8266.yaml
  dht22: !include .sensor.dht22.yaml