---
substitutions:
  name: "esp-naehzimmer"
  prefix: "Nähzimmer" 
  api_key: !secret naehzimmer_api_key
  ota_password: !secret naehzimmer_ota_password
  wifi_fallback_password: !secret naehzimmer_wifi_fallback_password

packages:
  device: !include .device.esp8266.yaml
  dht22: !include .sensor.dht22.yaml