---
substitutions:
  name: "esp-bad"
  prefix: "Bad" 
  api_key: !secret bad_api_key
  ota_password: !secret bad_ota_password
  wifi_fallback_password: !secret bad_wifi_fallback_password

packages:
  device: !include .device.esp8266.yaml
  dht22: !include .sensor.dht22.yaml