---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v4.1.0
      - name: Remove http configuration as this can't be tested without certificates
        uses: mikefarah/yq@master
        with:
          cmd: yq -i 'del(.http)' configuration.yaml
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4
        with:
          path: "."
          secrets: ./secrets.yaml.default
          version: "${{ matrix.version }}"

  esphome:
    name: ESPHome
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v4.1.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy secrets stub into configuration folder
        run: cp ./esphome/secrets.yaml.default ./esphome/secrets.yaml
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./esphome -type f -name "*.yaml" -maxdepth 1 -not -name "secrets.yaml" -not -name ".*"); do esphome config "${file}"; done
